name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: "C04CJTLP1AA"
          payload: |
            {
             "text": "New Release (In progress...)",
              "attachments": [
                {
                  "fallback": "New Release",
                  "title": "New Release",
                  "title_link": "https://api.slack.com/",
                  "text": "Optional text that appears within the attachment",
                  "pretext": "New release",
                  "footer": "Slack API",
                  "footer_icon": "https://platform.slack-edge.com/img/default_application_icon.png",
                  "color": "dbab09",
                  "blocks": [
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "This is a section block with an accessory image."
                      },
                      "accessory": {
                        "type": "image",
                        "image_url": "https://pbs.twimg.com/profile_images/625633822235693056/lNGUneLX_400x400.jpg",
                        "alt_text": "cute cat"
                      }
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      # - name: Notify Slack 2
      #   uses: slackapi/slack-github-action@v1.23.0
      #   with:
      #     channel-id: "C04CJTLP1AA"
      #     update-ts: ${{ steps.slack.outputs.ts }}
      #     payload: |
      #       {
      #         "text": "New Release (Finished)",
      #         "blocks": [
      #           {
      #             "type": "header",
      #             "text": {
      #               "type": "plain_text",
      #               "text": "New Release"
      #             }
      #           },
      #           {
      #             "type": "section",
      #             "text": {
      #               "type": "mrkdwn",
      #               "text": "New Typescript SDK release!!\n- test\n- test"
      #             },
      #             "accessory": {
      #               "type": "image",
      #               "image_url": "https://global-uploads.webflow.com/6047a9e35e5dc54ac86ddd90/638a6194ac02047047945a9b_pZ-iqEC6Xt0fVckLLkQnzwG47FucYgZcR40kNapNxSA.png",
      #               "alt_text": "Typescript"
      #             }
      #           },
      #           {
      #             "type": "context",
      #             "elements": [
      #               {
      #                 "type": "mrkdwn",
      #                 "text": "*Cat* has approved this message."
      #               }
      #             ]
      #           }
      #         ],
      #         "attachments": [
      #           {
      #             "pretext": "New release",
      #             "color": "28a745",
      #             "fields": [
      #               {
      #                 "title": "Status",
      #                 "short": true,
      #                 "value": "Published"
      #               }
      #             ]
      #           }
      #         ]
      #       }
      #   env:
      #     SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}


                  
                    # {
                    #   "title": "Status",
                    #   "short": true,
                    #   "value": "In progress"
                    # },
                    # {
                    #     "title": "Priority",
                    #     "value": "High",
                    #     "short": false
                    # }