name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: "C04CJTLP1AA"
          payload: |
            {
             "text": "New Release (In progress...)",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "New Release"
                  }
                }
              ],
              "attachments": [
                {
                  "pretext": "New release",
                  "color": "dbab09",
                  "fields": [
                    {
                      "title": "Status",
                      "short": true,
                      "value": "In progress"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      - name: Notify Slack 2
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: "C04CJTLP1AA"
          update-ts: ${{ steps.slack.outputs.ts }}
          payload: |
            {
              "text": "New Release (Finished)",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "New Release"
                  }
                }
              ],
              "attachments": [
                {
                  "pretext": "New release",
                  "color": "28a745",
                  "fields": [
                    {
                      "title": "Status",
                      "short": true,
                      "value": "Published"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
